### PR TITLE
Feature/authentication front back

### PR DESCRIPTION
**Pull request by pierrolabo**
**What this PR do?**

- Hash every data used to identify a user in database (facebook id, google id, email, password)
- Stop sending private informations from the database after login or authentication 
- If a user use a different kind of authentication, it's merged into the same user
- Guest Users: 
- When a GET or POST request is sent, we send an Unauthorized error ONLY ONCE this will Pop a login modal 
- If Guest user refresh its page, it will also pop a login modal on GET or POST request ONLY ONCE

- Logged User:
 - If a request fail as unauthorized, it will send an error then pop a login modal

- Others request:
 - If a request fail, we send an error that will be show in <STATUS/>

**What this PR don't do?**
- If a user is already authenticated ( token in local storage) and go to landing, he isn't redirected to main
- There's no logout button for the moment, when the design will be clear it will be easy to implement

### CODE REVIEW

**Comment by pierrolabo** [comment]
Hello Lily, thanks for your review.

The login/register works on my side, i think the problem come from a previous record in database.
I cleaned up the database, it will work for you now :)

I agree for the Private route refactor, i think we can verify the token on front-end with the same method, i'll try

Regarding prettier, could you send me your configuration file ?

**Comment by lily-law** [comment]
The login/register works now thanks.

I think maybe it's better verified as it is on the backend, but I think most the front end routes are better to leave as public and only verify/authenticate when a user action calls the backend for an operation that changes data or fetches user data not available to other users. 

This gives me an idea, we'll have to see what the team think but we could change the login from being on the landing into a modal/popup the the root view/App component (so it can popup in any page required). We could use the new services/serverAPI.mjs to control when authentication is required and pop up the modal if there is no valid token. This will mean users can try the app without any sign in required.

**Comment by lily-law** [comment]
So I don't have a Prettier config, but in the Prettier extension settings there's a checkbox for using single quotes in place of double

**Comment by pierrolabo** [comment]
> The login/register works now thanks.
> 
> I think maybe it's better verified as it is on the backend, but I think most the front end routes are better to leave as public and only verify/authenticate when a user action calls the backend for an operation that changes data or fetches user data not available to other users.
> 
> This gives me an idea, we'll have to see what the team think but we could change the login from being on the landing into a modal/popup the the root view/App component (so it can popup in any page required). We could use the new services/serverAPI.mjs to control when authentication is required and pop up the modal if there is no valid token. This will mean users can try the app without any sign in required.

Yep ! this what i was thinking about ! And making our routes accessible to everyone but only verifying for data modification or getting private data will make our app more user-friendly

**Pull request merged**
